/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ups.vista;

import ec.edu.ups.controlador.ControladorAdministrador;
import ec.edu.ups.controlador.ControladorUsuario;
import ec.edu.ups.modelo.Administrador;
import ec.edu.ups.modelo.Usuario;
import javax.swing.JOptionPane;

/**
 *
 * @author Anahi
 */
public class IniciarSesion extends javax.swing.JInternalFrame {

    private ControladorAdministrador controladorAdministrador;
    private ControladorUsuario controladorUsuario;
    private VentanaPrincipal ventanaPrincipal;
    
    public IniciarSesion(ControladorAdministrador controladorAdministrador,ControladorUsuario controladorUsuario,VentanaPrincipal ventanaPrincipal) {
        initComponents();
        
        this.controladorAdministrador=controladorAdministrador;
        this.controladorUsuario=controladorUsuario;
        this.ventanaPrincipal=ventanaPrincipal;
    }
    public void limpiar() {
        txtCorreo.setText("");
        txtPwd.setText("");
        txtRol.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnIniciarSesion = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        txtCorreo = new javax.swing.JTextField();
        txtPwd = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        txtRol = new javax.swing.JTextField();

        jLabel1.setText("Iniciar Sesión");

        jLabel2.setText("Correo Electrónico:");

        jLabel3.setText("Contraseña:");

        btnIniciarSesion.setText("Iniciar Sesión");
        btnIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarSesionActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jLabel4.setText("Rol (Usuario/Administrador):");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(26, 26, 26)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(btnIniciarSesion)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnCancelar)
                            .addComponent(txtCorreo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                            .addComponent(txtPwd, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(txtRol)))))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtPwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtRol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIniciarSesion)
                    .addComponent(btnCancelar))
                .addGap(0, 20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarSesionActionPerformed
        String correo = txtCorreo.getText();
        char[] contra = txtPwd.getPassword();
        String password = String.valueOf(contra);
        String opcion = txtRol.getText();
        
        if(correo.isEmpty()||password.isEmpty()||opcion.equalsIgnoreCase("Seleccione")){
            JOptionPane.showMessageDialog(this, "Llene todos los campos solicitados");
        }else{
            if (opcion.equals("Administrador")) {
                Administrador admin = controladorAdministrador.iniciarSesion(correo, password);
                if (admin != null) {
                    JOptionPane.showMessageDialog(this, "¡Sesion iniciada con exito!");
                    ventanaPrincipal.getCerrarSesionMenuItem().setVisible(true);
                    ventanaPrincipal.getFacturaMenuItem().setVisible(true);
                    ventanaPrincipal.getContratoMenuItem().setVisible(true);
                    ventanaPrincipal.getVehiculosMenuItem().setVisible(true);
                    ventanaPrincipal.getEspacioMenuItem().setVisible(true);
                    ventanaPrincipal.getUsuariosMenuItem().setVisible(true);
                    ventanaPrincipal.getClientesMenuItem().setVisible(true);
                    ventanaPrincipal.getGestionMenu().setVisible(true);
                    limpiar();
                    ventanaPrincipal.getIniciarSesionMenuItem().setVisible(false);
                    this.setVisible(false);
                }else{
                    JOptionPane.showMessageDialog(this, "Usuario no encontrado. Intentelo otra vez");
                }
            }else{
                Usuario usuario= controladorUsuario.iniciarSesion(correo, password);
                if (usuario != null) {
                    System.out.println(usuario);
                    JOptionPane.showMessageDialog(this, "¡Sesion iniciada con exito!");
                    ventanaPrincipal.getCerrarSesionMenuItem().setVisible(true);
                    ventanaPrincipal.getFacturaMenuItem().setVisible(true);
                    ventanaPrincipal.getContratoMenuItem().setVisible(true);
                    ventanaPrincipal.getVehiculosMenuItem().setVisible(true);
                    ventanaPrincipal.getEspacioMenuItem().setVisible(true);
                    ventanaPrincipal.getClientesMenuItem().setVisible(true);
                    limpiar();
                    ventanaPrincipal.getIniciarSesionMenuItem().setVisible(false);
                    this.setVisible(false);
                    
                    ventanaPrincipal.getGestionMenu().setVisible(true);
                    
                    
                } else {
                    JOptionPane.showMessageDialog(this, "Usuario no encontrado. Intentelo otra vez");
                }
            }
        }
    }//GEN-LAST:event_btnIniciarSesionActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnIniciarSesion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JPasswordField txtPwd;
    private javax.swing.JTextField txtRol;
    // End of variables declaration//GEN-END:variables
}
