/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ups.vista;

import ec.edu.ups.controlador.ControladorCliente;
import ec.edu.ups.controlador.ControladorEspacio;
import ec.edu.ups.controlador.ControladorFactura;
import ec.edu.ups.controlador.ControladorVehiculo;
import ec.edu.ups.modelo.Cliente;
import ec.edu.ups.modelo.Espacio;
import ec.edu.ups.modelo.Factura;
import ec.edu.ups.modelo.Vehiculo;
import java.time.LocalDateTime;
import java.util.Calendar;
import javax.swing.JOptionPane;

/**
 *
 * @author Anahi
 */
public class Ticket extends javax.swing.JInternalFrame {

    private ControladorCliente controladorCliente;
    private ControladorVehiculo controladorVehiculo;
    private ControladorEspacio controladorEspacio;
    private ControladorFactura controladorFactura;
    private String numero;
    private LocalDateTime local;
    
    public Ticket(ControladorFactura controladorFactura,ControladorEspacio controladorSitio,ControladorVehiculo controladorVehiculo,ControladorCliente controladorCliente) {
        initComponents();
        
        this.controladorFactura= controladorFactura;
        this.controladorEspacio= controladorSitio;
        this.controladorVehiculo=controladorVehiculo;
        this.controladorCliente= controladorCliente;
    }
    public int cargarCodigo() {
        int cod = controladorFactura.cargarCodigo();
        //txtCodigo.setText(String.valueOf(cod));
        return cod;
    }
    
    public void setNumero(String numero) {
        this.numero = numero;
    }

    public void CrearFactura(){
        int codigo= cargarCodigo();
        local = LocalDateTime.now();
        String estado="deuda";
        
        Calendar fechaIngreso = Calendar.getInstance();
        Espacio es= new Espacio(numero);
        Espacio espacio=this.controladorEspacio.leer(es);
        Vehiculo vehiculo = espacio.getVehiculo();
        Cliente cliente=vehiculo.getPropietario();
        
        Factura factura=new Factura(codigo, fechaIngreso,  cliente, espacio, estado);
        boolean respuesta= controladorFactura.crear(factura);
        
        String datos = "Tiket numero: "+codigo+"\nFecha y hora de ingreso: "+fechaIngreso.getTime()+"\nCliente: " +cliente.getNombre()+" "+cliente.getApellido()+"\nCedula: "+cliente.getCedula()+"\nPlaca vehiculo: "+vehiculo.getPlaca()+"\nMarca: "+vehiculo.getMarca()+"\nModelo: "+vehiculo.getModelo()+"\nNumero sitio parqueado: "+espacio.getNumero();
        txtTicket.setText(datos);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtTicket = new javax.swing.JTextArea();
        btnCerrar = new javax.swing.JButton();

        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        txtTicket.setColumns(20);
        txtTicket.setRows(5);
        jScrollPane1.setViewportView(txtTicket);

        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 373, Short.MAX_VALUE)
                .addGap(20, 20, 20))
            .addGroup(layout.createSequentialGroup()
                .addGap(159, 159, 159)
                .addComponent(btnCerrar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCerrar)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        CrearFactura();
    }//GEN-LAST:event_formInternalFrameActivated

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtTicket;
    // End of variables declaration//GEN-END:variables
}
