/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ups.vista;

import ec.edu.ups.controlador.ControladorAdministrador;
import ec.edu.ups.controlador.ControladorCliente;
import ec.edu.ups.controlador.ControladorContrato;
import ec.edu.ups.controlador.ControladorEspacio;
import ec.edu.ups.controlador.ControladorFactura;
import ec.edu.ups.controlador.ControladorUsuario;
import ec.edu.ups.controlador.ControladorVehiculo;
import javax.swing.JDesktopPane;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;

/**
 *
 * @author Anahi
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    private ControladorAdministrador controladorAdministrador;
    private ControladorUsuario controladorUsuario;
    private ControladorCliente controladorCliente;
    private ControladorVehiculo controladorVehiculo;
    private ControladorEspacio controladorEspacio;
    private ControladorFactura controladorFactura;
    private ControladorContrato controladorContrato;
    
    private GestionUsuario gestionUsuario;
    private IniciarSesion iniciarSesion;
    private GestionCliente gestionCliente;
    private GestionVehiculo gestionVehiculo;
    private InformacionEspacios informacionEspacios;
    private Ticket ticket;
    private VentanaFactura ventanaFactura;
    private VentanaContrato ventanaContrato;
    

    public VentanaPrincipal() {
        
        initComponents();
        controladorAdministrador = new ControladorAdministrador();
        controladorUsuario = new ControladorUsuario("datos/usuarios.obj");
        controladorCliente = new ControladorCliente("datos/cliente.obj");
        controladorVehiculo= new ControladorVehiculo("datos/vehiculo.obj");
        controladorEspacio= new ControladorEspacio("datos/espacios.obj");
        controladorFactura = new ControladorFactura("datos/facturas.obj");
        controladorContrato= new ControladorContrato("datos/contratos.obj");
        
        
        gestionUsuario = new GestionUsuario(controladorUsuario);
        gestionCliente= new GestionCliente(controladorCliente);
        gestionVehiculo= new GestionVehiculo(controladorVehiculo,controladorCliente,this,gestionCliente);
        ticket= new Ticket(controladorFactura,controladorEspacio,controladorVehiculo,controladorCliente);
        informacionEspacios= new InformacionEspacios(controladorCliente,controladorVehiculo,controladorEspacio,this,gestionVehiculo,ticket);
        ventanaFactura= new VentanaFactura(controladorFactura,controladorEspacio);
        ventanaContrato= new VentanaContrato(controladorContrato,controladorEspacio,controladorVehiculo,controladorCliente,this,gestionVehiculo);
        iniciarSesion= new IniciarSesion(controladorAdministrador,controladorUsuario, this);
        
        cerrarSesionMenuItem.setVisible(false);
        facturaMenuItem.setVisible(false);
        contratoMenuItem.setVisible(false);
        gestionMenu.setVisible(false);
        espacioMenuItem.setVisible(false); 
        ticketMenuItem.setVisible(false);
        desktopPane.add(ticket);
    }

        /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        inicioMenu = new javax.swing.JMenu();
        iniciarSesionMenuItem = new javax.swing.JMenuItem();
        cerrarSesionMenuItem = new javax.swing.JMenuItem();
        contratoMenuItem = new javax.swing.JMenuItem();
        facturaMenuItem = new javax.swing.JMenuItem();
        espacioMenuItem = new javax.swing.JMenuItem();
        ticketMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        gestionMenu = new javax.swing.JMenu();
        clientesMenuItem = new javax.swing.JMenuItem();
        usuariosMenuItem = new javax.swing.JMenuItem();
        vehiculosMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout desktopPaneLayout = new javax.swing.GroupLayout(desktopPane);
        desktopPane.setLayout(desktopPaneLayout);
        desktopPaneLayout.setHorizontalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );
        desktopPaneLayout.setVerticalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        inicioMenu.setMnemonic('f');
        inicioMenu.setText("Inicio");

        iniciarSesionMenuItem.setMnemonic('o');
        iniciarSesionMenuItem.setText("Iniciar Sesión");
        iniciarSesionMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciarSesionMenuItemActionPerformed(evt);
            }
        });
        inicioMenu.add(iniciarSesionMenuItem);

        cerrarSesionMenuItem.setMnemonic('s');
        cerrarSesionMenuItem.setText("Cerrar Sesión");
        cerrarSesionMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarSesionMenuItemActionPerformed(evt);
            }
        });
        inicioMenu.add(cerrarSesionMenuItem);

        contratoMenuItem.setMnemonic('a');
        contratoMenuItem.setText("Contratos");
        contratoMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contratoMenuItemActionPerformed(evt);
            }
        });
        inicioMenu.add(contratoMenuItem);

        facturaMenuItem.setText("Facturación");
        facturaMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                facturaMenuItemActionPerformed(evt);
            }
        });
        inicioMenu.add(facturaMenuItem);

        espacioMenuItem.setText("Espacios");
        espacioMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                espacioMenuItemActionPerformed(evt);
            }
        });
        inicioMenu.add(espacioMenuItem);

        ticketMenuItem.setText("Ticket");
        ticketMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ticketMenuItemActionPerformed(evt);
            }
        });
        inicioMenu.add(ticketMenuItem);

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Salir");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        inicioMenu.add(exitMenuItem);

        menuBar.add(inicioMenu);

        gestionMenu.setMnemonic('e');
        gestionMenu.setText("Gestionar");

        clientesMenuItem.setMnemonic('t');
        clientesMenuItem.setText("Clientes");
        clientesMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientesMenuItemActionPerformed(evt);
            }
        });
        gestionMenu.add(clientesMenuItem);

        usuariosMenuItem.setMnemonic('p');
        usuariosMenuItem.setText("Usuarios");
        usuariosMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuariosMenuItemActionPerformed(evt);
            }
        });
        gestionMenu.add(usuariosMenuItem);

        vehiculosMenuItem.setMnemonic('d');
        vehiculosMenuItem.setText("Vehículos");
        vehiculosMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vehiculosMenuItemActionPerformed(evt);
            }
        });
        gestionMenu.add(vehiculosMenuItem);

        menuBar.add(gestionMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(desktopPane)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void iniciarSesionMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciarSesionMenuItemActionPerformed
        desktopPane.add(iniciarSesion);
        iniciarSesion.setVisible(true);
    }//GEN-LAST:event_iniciarSesionMenuItemActionPerformed

    private void cerrarSesionMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarSesionMenuItemActionPerformed
        cerrarSesionMenuItem.setVisible(false);
        facturaMenuItem.setVisible(false);
        contratoMenuItem.setVisible(false);
        gestionMenu.setVisible(false);
        espacioMenuItem.setVisible(false);
        iniciarSesionMenuItem.setVisible(true);
    }//GEN-LAST:event_cerrarSesionMenuItemActionPerformed

    private void contratoMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contratoMenuItemActionPerformed
        desktopPane.add(ventanaContrato);
        ventanaContrato.setVisible(true);
    }//GEN-LAST:event_contratoMenuItemActionPerformed

    private void facturaMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_facturaMenuItemActionPerformed
        desktopPane.add(ventanaFactura);
        ventanaFactura.setVisible(true);
    }//GEN-LAST:event_facturaMenuItemActionPerformed

    private void espacioMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_espacioMenuItemActionPerformed
        desktopPane.add(informacionEspacios);
        informacionEspacios.setVisible(true);
    }//GEN-LAST:event_espacioMenuItemActionPerformed

    private void ticketMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ticketMenuItemActionPerformed
        desktopPane.add(ticket);
        ticket.setVisible(true);
    }//GEN-LAST:event_ticketMenuItemActionPerformed

    private void clientesMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientesMenuItemActionPerformed
        desktopPane.add(gestionCliente);
        gestionCliente.setVisible(true);
    }//GEN-LAST:event_clientesMenuItemActionPerformed

    private void usuariosMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuariosMenuItemActionPerformed
        desktopPane.add(gestionUsuario);
        gestionUsuario.setVisible(true);
    }//GEN-LAST:event_usuariosMenuItemActionPerformed

    private void vehiculosMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vehiculosMenuItemActionPerformed
        desktopPane.add(gestionVehiculo);
        gestionVehiculo.setVisible(true);
    }//GEN-LAST:event_vehiculosMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    public GestionUsuario getGestionUsuario() {
        return gestionUsuario;
    }

    public void setGestionUsuario(GestionUsuario gestionUsuario) {
        this.gestionUsuario = gestionUsuario;
    }

    public GestionCliente getGestionCliente() {
        return gestionCliente;
    }

    public void setGestionCliente(GestionCliente gestionCliente) {
        this.gestionCliente = gestionCliente;
    }

    public GestionVehiculo getGestionVehiculo() {
        return gestionVehiculo;
    }

    public void setGestionVehiculo(GestionVehiculo gestionVehiculo) {
        this.gestionVehiculo = gestionVehiculo;
    }

    public JMenu getGestionMenu() {
        return gestionMenu;
    }

    public void setGestionMenu(JMenu gestionMenu) {
        this.gestionMenu = gestionMenu;
    }
    

    public JMenuItem getCerrarSesionMenuItem() {
        return cerrarSesionMenuItem;
    }

    public void setCerrarSesionMenuItem(JMenuItem cerrarSesionMenuItem) {
        this.cerrarSesionMenuItem = cerrarSesionMenuItem;
    }

    public JMenuItem getClientesMenuItem() {
        return clientesMenuItem;
    }

    public void setClientesMenuItem(JMenuItem clientesMenuItem) {
        this.clientesMenuItem = clientesMenuItem;
    }

    public JMenuItem getContratoMenuItem() {
        return contratoMenuItem;
    }

    public void setContratoMenuItem(JMenuItem contratoMenuItem) {
        this.contratoMenuItem = contratoMenuItem;
    }

    public JMenuItem getEspacioMenuItem() {
        return espacioMenuItem;
    }

    public void setEspacioMenuItem(JMenuItem espacioMenuItem) {
        this.espacioMenuItem = espacioMenuItem;
    }

    public JMenuItem getExitMenuItem() {
        return exitMenuItem;
    }

    public void setExitMenuItem(JMenuItem exitMenuItem) {
        this.exitMenuItem = exitMenuItem;
    }

    public JMenuItem getFacturaMenuItem() {
        return facturaMenuItem;
    }

    public void setFacturaMenuItem(JMenuItem facturaMenuItem) {
        this.facturaMenuItem = facturaMenuItem;
    }

    public JMenuItem getIniciarSesionMenuItem() {
        return iniciarSesionMenuItem;
    }

    public void setIniciarSesionMenuItem(JMenuItem iniciarSesionMenuItem) {
        this.iniciarSesionMenuItem = iniciarSesionMenuItem;
    }

    public JMenu getInicioMenu() {
        return inicioMenu;
    }

    public void setInicioMenu(JMenu inicioMenu) {
        this.inicioMenu = inicioMenu;
    }
    public JMenuItem getTicketMenuItem() {
        return ticketMenuItem;
    }

    public void setTicketMenuItem(JMenuItem ticketMenuItem) {
        this.ticketMenuItem = ticketMenuItem;
    }

    public JMenuItem getUsuariosMenuItem() {
        return usuariosMenuItem;
    }

    public void setUsuariosMenuItem(JMenuItem usuariosMenuItem) {
        this.usuariosMenuItem = usuariosMenuItem;
    }

    public JMenuItem getVehiculosMenuItem() {
        return vehiculosMenuItem;
    }

    public void setVehiculosMenuItem(JMenuItem vehiculosMenuItem) {
        this.vehiculosMenuItem = vehiculosMenuItem;
    }

    public JDesktopPane getDesktopPane() {
        return desktopPane;
    }

    public void setDesktopPane(JDesktopPane desktopPane) {
        this.desktopPane = desktopPane;
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem cerrarSesionMenuItem;
    private javax.swing.JMenuItem clientesMenuItem;
    private javax.swing.JMenuItem contratoMenuItem;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuItem espacioMenuItem;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenuItem facturaMenuItem;
    private javax.swing.JMenu gestionMenu;
    private javax.swing.JMenuItem iniciarSesionMenuItem;
    private javax.swing.JMenu inicioMenu;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem ticketMenuItem;
    private javax.swing.JMenuItem usuariosMenuItem;
    private javax.swing.JMenuItem vehiculosMenuItem;
    // End of variables declaration//GEN-END:variables

}
